# fly.toml app configuration file generated for pemilu2024 on 2024-03-09T18:28:31+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pemilu2024'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
